### ISSUE TITLE
Cleanup Pages to Fix Images, Links, Remove HTML

### ISSUE THREAD

**Issue by BobGneu** [AdamsLair/duality-docs#2]
As things stand only two pages of the documentation site have had their links corrected. 

Images can be referenced using markdown similar to the following

## Inline Relative / Exact

```markdown
![Debug Game Break](../../img/GettingStarted/RunGameButton.png)
![Debug Game Break]({{site.baseurl}}/pages/img/GettingStarted/RunGameButton.png)
```

## Deferred Relative

```markdown
![Debug Game Break][DebugGameBreak]
![Debug Game Break][DebugGameBreakDirect]

[DebugGameBreak]: ../../img/GettingStarted/RunGameButton.png
[DebugGameBreakDirect]: {{site.baseurl}}/pages/img/GettingStarted/RunGameButton.png
```

The preference is to use the above, but in some circumstances where custom formatting or features are necessary we may need to return to standard html img tags. Any such usage should be reviewed though. The goal is still to refrain from using anything but markdown. 

```markdown
<img src="{{site.baseurl}}/pages/img/GettingStarted/RunGameButton.png" />
```

## ToDo

- [x] Review the remaining pages of the site to ensure that all images are correctly linked. 
- [x] Transform all images and links into markdown style and remove all HTML from markdown pages.
- [ ] Take inventory of any unreferenced images and delete them if they're no longer needed.

**Comment by ilexp** [comment]
Starting to work on this now in the [page-cleanup](https://github.com/ilexp/duality-docs/tree/feature/page-cleanup) feature branch in my fork of the repo.

**Comment by ilexp** [comment]
Done in first iteration. Closing this and moving the discussion to the [pending Pull Request](https://github.com/AdamsLair/duality-docs/pull/20).
