### ISSUE TITLE
Create and Customize Duality-Docs Jekyll Templates and Theme

### ISSUE THREAD

**Issue by BobGneu** [AdamsLair/duality-docs#3]
Github Pages leverages the [Jekyll] theme engine to render markdown and HTML into the pages site for the repository. Our goal is to exclusively write documentation in Markdown and to have a standard theme to be used throughout the site. 

## Relevant Links

* [Customizing GitHub Pages][GithubPages]
* [Adding a Jekyll theme to your GitHub Pages site][GithubJekyll]
* [Customizing CSS and HTML in your Jekyll theme][GithubJekyll2]
* [Pages Themes Home][Pages Themes]
* [Previous Discussion][PreviousDiscussion]

## ToDo
- [x] Work with the team to create a standardized template and theme
- [x] Should include Navigation/TOC, Sidebar, Header, Footer with appropriate links to the projects relevant endpoints like discord, forums, blog etc. 
- [x] Should demonstrate Jekyll template is functional - **Will require a fork.** 
- [x] Oversee Integration into origin repo
- [x] ~Needs to take Localized content into account~
- [x] ~Document any features that are leveraged or created beyond the standards in a new Contribution section of the documentation~ _No non-standard features used_

[PreviousDiscussion]: https://github.com/AdamsLair/duality/issues/589
[GithubPages]: https://help.github.com/categories/customizing-github-pages/
[GithubJekyll]: https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/
[GithubJekyll2]: https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/
[Pages Themes]: https://github.com/pages-themes

**Comment by ilexp** [comment]
I've started working on this in a [fork of the docs repo](https://github.com/ilexp/duality-docs). Current state is visible [here](https://ilexp.github.io/duality-docs/), heavily work in progress. I'm aiming for a responsive design that will work on both desktop screen resolutions and mobile. Some inspiration for layout and style: [Microsoft docs](https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-using-the-dotnet-cli).

**Comment by ilexp** [comment]
Removed multi-language as a requirement for now, as this can always be added later and there currently is no need or capacity to actually do all the translation. Keeping multi-version though, as this is a vital feature.

**Comment by ilexp** [comment]
### Progress

- Started setting up a basic layout with header / main / footer layout.
- Restructured the Jekyll templates a bit so each part has its own html file.
- Started defining a responsive CSS style.

### Immediate ToDo

- Cleanup the footer and fill it with useful content.
  - Also fix the footers link style.
- Introduce a sidebar that allows to navigate all main pages.
  - Vertical sidebar should turn into a header-like section on small devices / screen widths.
  - Use the Jekyll page front matter to identify which pages should be in the sidebar.
  - Allow each page to define sub-pages in the front matter, which will show up as sub items in the sidebar.
  - Use the sub-page feature for categorization and defining a page hierarchy.
  - The sidebar should only show parent, sibling and child levels relative to the current page, and highlight the currently opened one.
- Add Duality version identifiers to each pages front matter.
  - Adjust the sidebar, so it only displays pages that have the same Duality version as the current one.
- Make sure that every HTML page has a link to its markdown equivalent in the repo, so people can easily improve the docs.
- Introduce a breadcrumbs bar below the header, allowing to easily navigate upwards in the page hierarchy.
- Tweak and finalize the CSS style.
  - Change default link style to not do any size changes.
- Merge back.

**Comment by ilexp** [comment]
### Progress

- Cleaned up the footer style and content.
- Set up a two column layout.
- Changed link style to not change sizes on hover.
- Lots of minor style tweaks.
- Set up a basic responsive side / main layout.
- Merged back the latest version.

### ToDo

- Page titles should be displayed as main heading above the content.
- Make the sidebar contents responsive to smaller screen layouts.
  - Adapt to use more horizontal space than vertical space, if possible.
- Introduce a sidebar that allows to navigate all main pages.
  - Use the Jekyll page front matter to identify which pages should be in the sidebar.
  - Allow each page to define sub-pages in the front matter, which will show up as sub items in the sidebar.
  - Use the sub-page feature for categorization and defining a page hierarchy.
  - The sidebar should only show parent, sibling and child levels relative to the current page, and highlight the currently opened one.
- Add Duality version identifiers to each pages front matter.
  - Adjust the sidebar, so it only displays pages that have the same Duality version as the current one.
- Make sure that every HTML page has a link to its markdown equivalent in the repo, so people can easily improve the docs.
- Introduce a breadcrumbs bar below the header, allowing to easily navigate upwards in the page hierarchy.

**Comment by ilexp** [comment]
### Progress

- Page titles now appear as heading above the content.
- Responsive sidebar style that switches to a horizontal multi-column layout on small devices and screens.
- Initial sidebar script implementation, displaying top-level pages grouped by category.
- ~~Now switching to a feature branch model to avoid spamming the docs repo with lots of work-in-progress commits as done before.~~ _Seems like that doesn't work because GitHub only builds pages from master or gh-pages, no other branches possible._

### ToDo

- Finish sidebar implementation.
  - Display "back" link to parent page.
  - Display links to child pages.
  - Display a table of contents for the current page.
- Add front matter to all pages.
  - Category, Title, Priority
- Duality version support
  - Add version identifier to each pages front matter.
  - Filter displayed pages by version match to current page.
  - Display current pages version in the sidebar.
- Add an "edit" button / link to every page.
- Add an "add new" button that links to a "how to add new pages" markdown file in the repo.
- Add breadcrumbs bar right above the main content to ease navigation.

**Comment by ilexp** [comment]
### Progress

- Added front matter to all pages.
- Introduced explicit top-level category list, naming and sorting.

### ToDo

- Fix accidental top margin for sidebar via `vertical-align: top`, see [here](https://stackoverflow.com/questions/11446839/css-table-cell-contents-have-unnecessary-top-margin).
- Improve horizontal flow look of sidebar by tweaking local headline margins and `ul` text align.
- Fix footer spacing in low-width style.
- Finish sidebar implementation.
  - Display "back" link to parent page.
  - Display links to child pages.
  - Display a table of contents for the current page, potentially separate and following scrolling.
- Duality version support
  - Add version identifier to each pages front matter.
  - Filter displayed pages by version match to current page.
  - Display current pages version in the sidebar.
- Add an "edit" button / link to every page.
- Add an "add new" button that links to a "how to add new pages" markdown file in the repo.
- Add breadcrumbs bar right above the main content to ease navigation.
- Add a content page table style that switches from regular table columns to sequential table columns on very small devices / screens.
- Improve inline code style, make it more distinguishable from regular text.
- Improve syntax highlighting color scheme, if easily possible.

**Comment by ilexp** [comment]
### Progress

- Fixed sidebar top margin.
- Improved horizontal flow appearance of sidebar in low-width mode.
- Fixed footer style in low-width mode.
- Added "Add Page", "Edit Page" and "Contribute" buttons.

### ToDo

- Finish sidebar implementation.
  - Display "back" link to parent page.
  - Display links to child pages.
  - Display a table of contents for the current page, potentially separate and following scrolling.
- Duality version support
  - Add version identifier to each pages front matter.
  - Filter displayed pages by version match to current page.
  - Display current pages version in the sidebar.
- Add breadcrumbs bar right above the main content to ease navigation.
- Add a content page table style that switches from regular table columns to sequential table columns on very small devices / screens.
- Improve inline code style, make it more distinguishable from regular text.
- Improve syntax highlighting color scheme, if easily possible.

**Comment by ilexp** [comment]
### Progress

- Set up a "Guidelines" parent for "Best Practices" and "Common Pitfalls" as a test case for parent / child support.
- The sidebar now displays parent and child pages, if defined.

### ToDo

- Duality version support
  - Add version identifier to each pages front matter.
  - Sidebar: Filter queried pages by version match to current page.
  - Display current pages version in the sidebar.
  - Consider displaying links for other versions of the current page in the sidebar.
- Improve inline code style, make it more distinguishable from regular text.
- Improve syntax highlighting color scheme, if easily possible.
- Improve overall readability in [mobile devices](https://mydevice.io/devices/).
  - Sidebar links should jump to page begin (use anchor?)
  - Too much `ul` padding left.
  - Slightly reduce margins left / right?
  - Add a content page table style that switches from regular table columns to sequential table columns on very small devices / screens.
- Investigate adding a table of contents to the sidebar.
  - Should be 100% Jekyll / Liquid, no JS.
  - Probably separate and following scrolling.
  - Disable when collapsing sidebar into content area.

**Comment by ilexp** [comment]
### Progress

- Added version identifier to each pages front matter.
- Added version filter support to sidebar.
- Added sibling display to sidebar for pages with a parent, but no children.
- Version switch links at the bottom of the sidebar.

### ToDo

- Consider increasing sidebar item margins slightly.
- Improve inline code style, make it more distinguishable from regular text.
- Improve syntax highlighting color scheme, if easily possible.
- Improve overall readability in [mobile devices](https://mydevice.io/devices/).
  - Sidebar links should jump to page begin (use anchor?)
  - Too much `ul` padding left.
  - Slightly reduce margins left / right?
  - Add a content page table style that switches from regular table columns to sequential table columns on very small devices / screens.
- Put the Duality logo somewhere and check if there's a way to get some orange into the design.
- Investigate adding a table of contents to the sidebar.
  - Should be 100% Jekyll / Liquid, no JS.
  - Probably separate and following scrolling.
  - Disable when collapsing sidebar into content area.

**Comment by ilexp** [comment]
### Progress

- Orange color style for the site title.
- Slightly increased sidebar item margins.
- Improved inline and block code style, as well as syntax highlighting.

### ToDo

- Improve overall readability in [mobile devices](https://mydevice.io/devices/).
  - Sidebar links should jump to page begin (use anchor?)
  - Too much `ul` padding left.
  - Slightly reduce margins left / right?
  - Add a content page table style that switches from regular table columns to sequential table columns on very small devices / screens.
- Add a site icon.
- Put the Duality logo somewhere if possible.
- Investigate adding a table of contents to the sidebar.
  - Should be 100% Jekyll / Liquid, no JS.
  - Probably separate and following scrolling.
  - Disable when collapsing sidebar into content area.

**Comment by ilexp** [comment]
### Progress

- Improved mobile / low-width device readability as described in the previous ToDos. Transposing tables via CSS proved too unstable though, so reduced font size and padding instead.
- Added markdown TOC style, and a sample TOC to the getting started article. Discarded the idea of a sidebar TOC, as the sidebar is already crowded with page nav.
- Added a site favicon.

### ToDo

- Put the Duality logo somewhere if possible. Probably in the footer?
- Squash-merge back recent changes via PR to test the new, protected-branch workflow.

**Comment by ilexp** [comment]
### Progress

- Tried to put a Duality logo in the footer, but gave up after several tries of making it match the color scheme. Also looked at a bright footer alternative, but discarded the idea after it just looked worse. It'll have to do without a Duality logo for now.

Ready for merging. Closing this issue to continue with PR #14.
