### ISSUE TITLE
Add GitHub Pull Request and Issue Templates

### ISSUE THREAD

**Issue by BobGneu** [AdamsLair/duality-docs#5]
Create `.github\` templates where relevant. 

## ToDo
- [x] ~Work with team to establish expected standards~ _See PR_
- [x] ~Proof read templates~ _See PR_
- [x] [pull_request_template.md]
- [x] [issue_template.md]

[issue_template.md]: https://help.github.com/articles/creating-an-issue-template-for-your-repository/
[pull_request_template.md]: https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by ilexp** [comment]
Created both templates and submitted a PR (#18). Closing this issue in order to continue with review and further iterations on the PR itself.
