### ISSUE TITLE
Decommission Old Duality Wiki

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality-docs#6]
After the new docs page is ready to be used and contributed to, decommission the old wiki and supersede it with the docs page / repo combo.

## ToDo
- [x] Replace the content of all pages in the old Duality wiki with a redirect link to their equivalent on the new docs website. Make sure to also replace the starting page and remove the sidebar, so it is no longer intuitive to open any of the old wiki pages.
- [x] Introduce a new `dualitydocs.adamslair.net` subdomain to redirect to the new docs page and use it wherever the wiki was previously linked. Especially check the [main info page](https://duality.adamslair.net).
- [x] Update all existing subdomains to point to the new docs pages.

**Comment by ilexp** [comment]
Done. The new docs pages are now live.
