### ISSUE TITLE
Add a README.md File

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality-docs#7]
In order to make the repository more contribution-friendly, add a README.md file.

## ToDo
- [x] Brief introduction / summary paragraph.
- [x] Paragraph about contributing.
  - Contributions welcome.
  - What to contribute.
  - How to contribute.
  - Link the article on how to do a local Jekyll setup for GitHub pages: [Here](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/)
- [x] Link to Duality info page.

**Comment by ilexp** [comment]
Started working on this in my fork on the [`feature/readme` branch](https://github.com/ilexp/duality-docs/tree/feature/readme).

**Comment by ilexp** [comment]
Done and ready for review. Closing this as we move discussion forward to the linked PR.
